repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.2
    hooks:
      - id: jupytext
        args: [ '--sync' ] # Add this line
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace